### PR TITLE
Use NPM as default package manager

### PR DESCRIPTION
**Pull request by jonkoops**
Switches the package manager from Yarn to NPM. This replaces the old Yarn lockfile with an NPM version. There are a couple of reasons for doing this:

1. I'll be introducing some automation using GitHub Actions, this simplifies the setup needed for it.
2. It makes things more familiar for external contributors (for example, see #67, where multiple lock files are checked in).
3. All features we would need that Yarn supports are also in NPM now, making it less useful.

### CODE REVIEW

**Comment by jonkoops** [comment]
@thgh if you feel comfortable with giving me merge rights, I can move this along without a review. I'll be putting out quite a couple of PRs to keep things reviewable, so it could be favorable to do so.

If you prefer to review them individually before merging, that is also fine by me. Let me know what works for you.

**Comment by jonkoops** [comment]
Side-note, this PR should be merged before any PRs that modify the package file (such as #82 and #83), as these will influence the lockfile as well.

**Comment by thgh** [comment]
I would recommend against this. I don't agree with your reasons. If you can automate testing by switching to NPM, that's a good reason though!

As a collaborator, I think you have merge rights. The main branch requires a review though.

Ideally, you create 1 PR with all changes required to fix the types issue. If a PR doesn't fix something, I'm hesitant to merge. Don't fix what's not broken.

**Comment by jonkoops** [comment]
My main reason for this is that when setting up automation I will not have to set up Yarn. For example, [`actions/setup-node`](https://github.com/actions/setup-node) assumes NPM and installing Yarn is another step that is not required.

> Ideally, you create 1 PR with all changes required to fix the types issue.

I'll do this separately. I like to make breaking changes explicit commits, so the changelog can be easily compiled from the commit history.

**Comment by thgh** [comment]
setup-node installs yarn by default, will close this as you can do this in the @rollup/plugins repo

**Pull request closed without merging**
